title: Tianer Zhou
description: Physical intelligence
url: "https://zhoutianer.github.io"
baseurl: ""
author: Zireael

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

show_excerpts: true

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/ezhoureal"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/tianer-zhou/"
